### ISSUE TITLE
how can i get 1024 dimensions of each frame?

### ISSUE THREAD

**Issue by linjingxu** [antoine77340/video_feature_extractor#4]
when i use pretrained 3D_resnext101 model, the dimensions of each frame is 2048. How can i get 1024 dimensions？

**Comment by antoine77340** [comment]
Why would you need 1024 ? The feature dimension for ResNet and ResNext is 2048.

**Comment by JasperLS** [comment]
What exactly do these 2048 dimensions represent?

**Comment by antoine77340** [comment]
It is the global average pooled output that you have just before the last linear layer.

**Comment by JasperLS** [comment]
so, in a sense, if you have 1024 dimensions you're interested in, @linjingxu, you could just add a layer of 1024 dimensions on the 2048 outputs, assuming you have labeled your video data in 1024 dims..

**Comment by wangying1586** [comment]
![image](https://user-images.githubusercontent.com/52782861/86190266-80395f00-bb76-11ea-87c9-2a41a7604cfd.png)
![image](https://user-images.githubusercontent.com/52782861/86190429-e920d700-bb76-11ea-9e58-4f225a0e93d1.png)

Could you help me to look at this problem? This is my debugger's result. Why in "loader" i didn't get any video tensor????   decoding video failed

**Comment by wangying1586** [comment]
![image](https://user-images.githubusercontent.com/52782861/86190760-d8249580-bb77-11ea-92b8-9b0cc5c7f86e.png)
This is my .csv file.  What should i do with this ??   Is there any problems?

**Comment by antoine77340** [comment]
Is ffprobe working on these videos ? Maybe to be sure that the path is correct, please replace the path with absolute path instead of relative path ?

**Comment by wangying1586** [comment]
> Is ffprobe working on these videos ? Maybe to be sure that the path is correct, please replace the path with absolute path instead of relative path ?

thanks i got it！！
